name: 🖼️ Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: upcloud
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: pwd
#      - name: Deploy 🚀
#        uses: appleboy/scp-action@v0.1.2
#        with:
#          strip_components: 3
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          port: ${{ secrets.PORT }}
#          source: ${{ github.workspace }}
#          target: '/home/chores/todo'
