name: 🖼️ Release
on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  appName: todo

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: hetzner
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.run_number }} .
      - run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            podman container kill ${{ env.appName }} 
            podman container rm ${{ env.appName }}

            podman image prune -af
            podman image pull ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.run_number }}

            mkdir -p ${{ env.appName }}
            cd ${{ env.appName }}

            podman run \
              --name ${{ env.appName }} \
              -p 5000:3000 \
              --restart unless-stopped \
              --env "NODE_ENV=production" \
              --env "DATABASE_URL=file:/db/${{ env.appName }}.sqlite" \
              --env "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" \
              --env "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" \
              --env "ONE_SIGNAL_APP=${{ secrets.ONE_SIGNAL_APP }}" \
              --env "ONE_SIGNAL_KEY=${{ secrets.ONE_SIGNAL_KEY }}" \
              -d \
              -v "$(pwd)/db:/db" ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
