name: 🖼️ Release
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: upcloud
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: pwd
      - run: echo $GITHUB_WORKSPACE
      - run: sshpass
      - run: sshpass -p $PASSWORD rsync  -e "ssh -o StrictHostKeyChecking=no" -avzh . $TARGET
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          TARGET: ${{ secrets.RSYNC_TARGET }}